# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 11:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kladr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic_region_id', models.PositiveIntegerField(verbose_name='id региона в базе NIC')),
                ('ip_left', models.BigIntegerField(db_index=True, verbose_name='левая граница')),
                ('ip_right', models.BigIntegerField(db_index=True, verbose_name='правая граница')),
                ('ip_range', models.CharField(max_length=256, verbose_name='промежуток IP-адресов')),
                ('longitude', models.CharField(max_length=256, verbose_name='долгота')),
                ('latitude', models.CharField(max_length=256, verbose_name='широта')),
                ('kladr_code', models.CharField(db_index=True, max_length=17, validators=[django.core.validators.RegexValidator(code='nomatch', message='Kladr Core Error', regex='^(\\d{13})|(\\d{17})|(\\d{19})$')], verbose_name='Код КЛАДРа')),
                ('kladr_name', models.CharField(max_length=1024, verbose_name='населенный пункт')),
                ('kladr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kladr', to='kladr.Kladr', verbose_name='Kladr')),
            ],
        ),
    ]
