version: "3"

services:
  # NGINX
  nginx:
    image: graphmarket/nginx_pw
    restart: unless-stopped
    hostname: nginx
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    env_file:
      - env/nginx
    ports:
      - "80:80"
      - "443:443"
      - "8282:8282"
    volumes:
      - /var/president_media/presidentwatches-original:/media
    links:
      - "web:web"
    depends_on:
      - web

  web:
    image: graphmarket/server_pw
    restart: unless-stopped
    hostname: web
    build:
      context: .
      dockerfile: ./compose/server/Dockerfile
    env_file:
      - env/web
    volumes:
      - /var/president_media:/var/president_media
      - /var/graph_market:/var/graph_market
    links:
      - postgres_web:postgres
      - geo:geo
    depends_on:
      - postgres_web
      - geo
      - celery_pw

  celery_pw:
    image: graphmarket/celery_pw
    restart: unless-stopped
    hostname: web
    build:
      context: .
      dockerfile: ./compose/celery_pw/Dockerfile
    env_file:
      - env/web
    volumes:
      - /var/president_media:/var/president_media
    links:
      - postgres_web:postgres
    depends_on:
      - postgres_web

  elasticsearch:
    image: graphmarket/elasticsearch-pw
    restart: unless-stopped
    hostname: elasticsearch
    volumes:
      - /var/graph_market:/var/graph_market

  # GEO Service
  geo:
    image: graphmarket/geo_pw:latest
    restart: unless-stopped
    hostname: geo
    build:
      context: .
      dockerfile: ./compose/geo/Dockerfile
    env_file:
      - env/geo
    links:
      - rabbit
      - redis
    depends_on:
      - rabbit
      - redis

  # RABBITMQ
  rabbit:
    image: rabbitmq:3.8-rc-management-alpine
    restart: unless-stopped
    hostname: rabbit
    volumes:
      - "./env/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:rw"
      - "./env/rabbit_definitions.json:/etc/rabbitmq/definitions.json:rw"
  
  # Redis
  redis:
    image: redis:latest
    restart: unless-stopped
    hostname: redis

  postgres_web:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - /var/postgresql_web/data2:/var/postgresql_web/data2
    env_file:
      - env/postgres_web

  postgres_geo:
    image: postgres:latest
    restart: unless-stopped
    shm_size: 3gb
    volumes:
      - /var/postgresql_geo/data:/var/postgresql_geo/data
    env_file:
      - env/postgres_geo