# Generated by Django 2.1.4 on 2019-05-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='_author_city',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
