# Generated by Django 2.1.4 on 2019-08-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20190810_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
