# Generated by Django 2.1.4 on 2019-08-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20190810_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='email',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
