# Generated by Django 2.1.4 on 2019-05-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20190529_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveIntegerField(choices=[(10, '10'), (9, '9'), (8, '8'), (7, '7'), (6, '6'), (5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1'), (0, '0')], default=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Новый'), (2, 'Одобрен'), (3, 'Отклонен'), (4, 'Архивирован')], default=1),
        ),
    ]
