# Generated by Django 2.1.4 on 2019-05-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20190529_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='signature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
