# Generated by Django 2.1.4 on 2019-06-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20190530_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Новый'), (2, 'Одобрен'), (3, 'Отклонен'), (4, 'Архивирован')], default=2),
        ),
    ]
