# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 11:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kladr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Kladr Core Error', regex='^(\\d{13})|(\\d{17})|(\\d{19})$')], verbose_name='Код КЛАДРа')),
                ('code_subject', models.PositiveSmallIntegerField(default=0, verbose_name='Код Субьекта')),
                ('code_region', models.PositiveSmallIntegerField(default=0, verbose_name='Код Региона')),
                ('code_city', models.PositiveSmallIntegerField(default=0, verbose_name='Код Города')),
                ('code_locality', models.PositiveSmallIntegerField(default=0, verbose_name='Код Района')),
                ('code_street', models.PositiveSmallIntegerField(default=0, verbose_name='Код улицы')),
                ('code_relevance', models.PositiveSmallIntegerField(default=0, verbose_name='Код Актуальности')),
                ('name', models.CharField(db_index=True, max_length=1024, verbose_name='Название')),
                ('full_name', models.CharField(db_index=True, default='', max_length=6144, verbose_name='Полное Название')),
                ('kladr_type_socr', models.CharField(max_length=256, verbose_name='Тип объекта(сокращение)')),
                ('kladr_type', models.CharField(max_length=256, verbose_name='Тип объекта(полное имя)')),
                ('index', models.PositiveIntegerField(blank=True, default=0, verbose_name='Почтовый индекс')),
                ('houses_num', models.PositiveIntegerField(default=0, verbose_name='Почтовый индекс')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 Не центр'), (1, '1 Центр района'), (2, '2 Центр (столица) региона'), (3, '3 Центр района и региона (1+2)'), (4, '4 Центральный район центра региона')], default=0, validators=[djchoices.choices.ChoicesValidator({0: '0 Не центр', 1: '1 Центр района', 2: '2 Центр (столица) региона', 3: '3 Центр района и региона (1+2)', 4: '4 Центральный район центра региона'})], verbose_name='Статус объекта')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Предок', to='kladr.Kladr')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
