# Generated by Django 2.1.4 on 2018-12-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
