# Generated by Django 2.1.4 on 2019-04-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='search_scoring',
            field=models.PositiveIntegerField(default=10, verbose_name='поисковый скоринг'),
        ),
    ]
