# Generated by Django 2.1.4 on 2019-05-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productpage_search_scoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='search_scoring',
            field=models.PositiveIntegerField(default=10, verbose_name='поисковый скоринг'),
        ),
    ]
