# Generated by Django 2.1.4 on 2019-01-09 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190108_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribute',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attribute',
            name='modified_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='last modification date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribute',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attributegroup',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='modified_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='last modification date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
