# Generated by Django 2.1.4 on 2019-07-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideo',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='productvideo',
            unique_together={('product', 'slug')},
        ),
    ]
