# Generated by Django 2.1.4 on 2018-12-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productpage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributegroup',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
