# Generated by Django 2.1.4 on 2019-05-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_categorypage_search_scoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
