# Generated by Django 2.1.4 on 2019-07-24 15:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190723_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='summary',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
