# Generated by Django 2.1.4 on 2019-01-09 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190109_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributegroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attributegroup',
            name='modified_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='last modification date'),
            preserve_default=False,
        ),
    ]
