# Generated by Django 2.1.4 on 2018-12-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_attributegroup_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_set', to='shop.AttributeGroup'),
        ),
    ]
