# Generated by Django 2.1.4 on 2019-06-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productpage_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='_purchase_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
