# Generated by Django 2.1.4 on 2018-12-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181217_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='is_yml_offer',
            field=models.BooleanField(default=False),
        ),
    ]
