# Generated by Django 2.1.4 on 2019-02-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=2048, unique=True)),
                ('scoring', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modified_at', models.DateTimeField(blank=True, verbose_name='last modification date')),
                ('order', models.IntegerField(default=0)),
                ('_title', models.CharField(blank=True, max_length=512)),
                ('_meta_title', models.CharField(blank=True, max_length=256)),
                ('_meta_keywords', models.CharField(blank=True, max_length=256)),
                ('_meta_description', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
