# Generated by Django 2.1.4 on 2018-12-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productpage_is_yml_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='manual',
            field=models.FileField(blank=True, null=True, upload_to='manuals'),
        ),
    ]
