# Generated by Django 2.1.4 on 2019-07-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productpage__purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='rr_node',
            field=models.BooleanField(default=False),
        ),
    ]
