# Generated by Django 2.1.4 on 2019-07-11 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_categorypage_rr_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNodeRetailRocketRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_node', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rr_input_node_reverse', to='shop.CategoryPage')),
                ('output_node', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rr_output_node_reverse', to='shop.CategoryPage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='categorypage',
            name='rr_nodes',
            field=models.ManyToManyField(blank=True, related_name='rr_outputs', through='shop.CategoryNodeRetailRocketRelation', to='shop.CategoryPage'),
        ),
    ]
