# Generated by Django 2.1.4 on 2019-08-10 15:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='rating_overall',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[{'count': 0, 'percentage': 0, 'rating': 5}, {'count': 0, 'percentage': 0, 'rating': 4}, {'count': 0, 'percentage': 0, 'rating': 3}, {'count': 0, 'percentage': 0, 'rating': 2}, {'count': 0, 'percentage': 0, 'rating': 1}]),
        ),
    ]
