# Generated by Django 2.1.4 on 2018-12-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20181218_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='strict_options',
            field=models.BooleanField(default=True),
        ),
    ]
