# Generated by Django 2.1.4 on 2019-02-16 16:17

import core.db.fields.description
import core.db.fields.name
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_categorypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='description',
            field=core.db.fields.description.DescriptionField(blank=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='categorypage',
            name='name',
            field=core.db.fields.name.NameField(blank=True, max_length=512, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=2048, unique=True),
        ),
    ]
