# Generated by Django 2.1.4 on 2019-02-17 12:31

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190216_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryValueRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='categorypage',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='shop.CategoryPage'),
        ),
        migrations.AddField(
            model_name='categoryvaluerelation',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.CategoryPage'),
        ),
        migrations.AddField(
            model_name='categoryvaluerelation',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.AttributeValue'),
        ),
        migrations.AddField(
            model_name='categorypage',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='categories', through='shop.CategoryValueRelation', to='shop.AttributeValue'),
        ),
    ]
