# Generated by Django 2.1.4 on 2018-12-18 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_attribute_strict_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductValueRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductPage')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.AttributeValue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productpage',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='product_set', through='shop.ProductValueRelation', to='shop.AttributeValue'),
        ),
    ]
