# Generated by Django 2.1.4 on 2019-02-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190217_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=512),
        ),
        migrations.AddField(
            model_name='productpage',
            name='series',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
