# Generated by Django 2.1.4 on 2018-12-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20181218_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='value_bool',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
