# Generated by Django 2.1.4 on 2019-12-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productpage_has_club_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='has_gift_price',
            field=models.BooleanField(default=False),
        ),
    ]
