# Generated by Django 2.1.4 on 2019-03-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190217_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='slug',
            new_name='key',
        ),
    ]
