# Generated by Django 2.1.4 on 2019-12-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_GiftPrices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='summary',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
