# Generated by Django 2.1.7 on 2019-03-27 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_productpage_sale_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNodeInputRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_node', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_node_reverse', to='shop.CategoryPage')),
                ('output_node', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_node_reverse', to='shop.CategoryPage')),
            ],
        ),
        migrations.AddField(
            model_name='categorypage',
            name='inputs',
            field=models.ManyToManyField(blank=True, related_name='outputs', through='shop.CategoryNodeInputRelation', to='shop.CategoryPage'),
        ),
        migrations.AlterUniqueTogether(
            name='categorynodeinputrelation',
            unique_together={('input_node', 'output_node')},
        ),
    ]
