# Generated by Django 2.1.7 on 2019-03-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_categorypage__depth'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNodeOutdatedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modified_at', models.DateTimeField(blank=True, verbose_name='last modification date')),
                ('slug', models.CharField(blank=True, db_index=True, max_length=2048, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
