# Generated by Django 2.1.7 on 2019-04-03 14:18

from django.db import migrations
import eav.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_categorynodeoutdatedurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='key',
            field=eav.fields.EavSlugField(blank=True),
        ),
    ]
