# Generated by Django 2.1.7 on 2019-04-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_attributevalue_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorynodeoutdatedurl',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.CategoryPage'),
        ),
    ]
