# Generated by Django 2.1.7 on 2019-04-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_categorynodeoutdatedurl_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='measure',
            field=models.CharField(blank=True, max_length=255, verbose_name='единица змерения'),
        ),
    ]
