# Generated by Django 2.1.7 on 2019-04-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20190403_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='key',
        ),
    ]
