# Generated by Django 2.1.7 on 2019-04-03 18:46

from django.db import migrations
import eav.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_attributevalue_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='key',
            field=eav.fields.EavSlugField(blank=True, max_length=255, unique=True),
        ),
    ]
