# Generated by Django 2.1.7 on 2019-04-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_attributevalue_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='key',
        ),
    ]
