# Generated by Django 2.1.4 on 2019-09-19 16:41

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_uuid',
            field=models.CharField(default=users.models.generate_uuid, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=users.models.generate_uuid, max_length=64),
        ),
    ]
