# Generated by Django 2.1.4 on 2019-10-26 15:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMarketingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, unique=True)),
                ('sales', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('automatically_increase', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.UserMarketingGroup'),
        ),
    ]
