# Generated by Django 2.1.4 on 2019-10-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191026_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermarketinggroup',
            name='ranking',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermarketinggroup',
            name='userscore_threshold',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
