# Generated by Django 2.1.4 on 2019-11-05 15:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191026_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermarketinggroup',
            name='sales',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
