# Generated by Django 2.1.4 on 2019-11-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191105_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermarketinggroup',
            options={'ordering': ['id']},
        ),
    ]
