# Generated by Django 2.1.4 on 2019-11-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191106_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscribeBlacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, unique=True)),
            ],
        ),
    ]
