version: '3'

services:
  rabbit:
    restart: unless-stopped
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=8800
      - RABBITMQ_DEFAULT_PASS=8800pass
      - RABBITMQ_DEFAULT_VHOST=8800vh
    ports:
      - "5672:5672"

  redis:
    restart: unless-stopped
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"
