# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kladr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_code', models.CharField(max_length=512, unique=True, verbose_name='ID по их базам')),
                ('delivery_type', models.PositiveSmallIntegerField(choices=[(0, 'Не указано'), (1, 'SDEK пункт выдачи'), (2, 'SDEK - курьерская доставка'), (3, 'PICKPOINT пункт выдачи')], default=0, verbose_name='Тип Службы доставки')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('city', models.CharField(max_length=1024, verbose_name='Город')),
                ('address', models.CharField(max_length=6144, verbose_name='Адрес')),
                ('opening_hours', models.CharField(max_length=1024, verbose_name='Часы работы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('delivery_price', models.PositiveIntegerField(default=0, verbose_name='Цена доставки')),
                ('delivery_time', models.CharField(max_length=512, verbose_name='Время доставки')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('kladr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kladr.Kladr', verbose_name='КЛАДР')),
            ],
        ),
        migrations.CreateModel(
            name='PickPointCityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.PositiveIntegerField(unique=True, verbose_name='ID В базе сдека')),
                ('city_name', models.CharField(max_length=512, verbose_name='Город')),
                ('obl_name', models.CharField(max_length=512, verbose_name='Область')),
                ('kladr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kladr.Kladr', verbose_name='КЛАДР')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SdekCityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.PositiveIntegerField(unique=True, verbose_name='ID В базе сдека')),
                ('city_name', models.CharField(max_length=512, verbose_name='Город')),
                ('obl_name', models.CharField(max_length=512, verbose_name='Область')),
                ('full_name', models.CharField(max_length=1024, verbose_name='Полное имя')),
                ('center', models.BooleanField(default=False, verbose_name='Центр')),
                ('kladr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kladr.Kladr', verbose_name='КЛАДР')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
