# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delete_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdekcitylist',
            name='price_sd_ex_1kg',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sdekcitylist',
            name='price_sd_ex_additional_kg',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sdekcitylist',
            name='price_sd_pkg_3kg',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sdekcitylist',
            name='price_sd_pkg_additional_kg',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sdekcitylist',
            name='price_ss_ex_1kg',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sdekcitylist',
            name='price_ss_ex_additional_kg',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sdekcitylist',
            name='price_ss_pkg_3kg',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sdekcitylist',
            name='price_ss_pkg_additional_kg',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sdekcitylist',
            name='time_max_sd_ex',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sdekcitylist',
            name='time_max_sd_pkg',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sdekcitylist',
            name='time_max_ss_ex',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sdekcitylist',
            name='time_max_ss_pkg',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sdekcitylist',
            name='time_min_sd_ex',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sdekcitylist',
            name='time_min_sd_pkg',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sdekcitylist',
            name='time_min_ss_ex',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sdekcitylist',
            name='time_min_ss_pkg',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
