# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delivery_citys_kladr_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickpointcitylist',
            name='kladr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kladr.Kladr', verbose_name='КЛАДР'),
        ),
        migrations.AlterField(
            model_name='sdekcitylist',
            name='kladr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kladr.Kladr', verbose_name='КЛАДР'),
        ),
    ]
