# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-25 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kladr', '0001_initial'),
        ('delivery', '0006_sdekcitylist_cash_on_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySdekPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Имя')),
                ('code', models.CharField(max_length=512, unique=True)),
                ('latitude', models.CharField(max_length=512)),
                ('longitude', models.CharField(max_length=512)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('is_payment_by_card', models.BooleanField(default=True)),
                ('is_payment_by_cash', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.SdekCityList')),
                ('kladr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kladr.Kladr')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
