# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-25 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kladr', '0001_initial'),
        ('delivery', '0007_deliverysdekpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPickPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Имя')),
                ('code', models.CharField(max_length=512, unique=True)),
                ('latitude', models.CharField(max_length=512)),
                ('longitude', models.CharField(max_length=512)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('is_payment_by_card', models.BooleanField(default=True)),
                ('is_payment_by_cash', models.BooleanField(default=True)),
                ('pvz_type', models.PositiveIntegerField(choices=[(1, 'АПТ'), (2, 'ПВЗ')], default=1)),
                ('max_box_size', models.CharField(blank=True, max_length=512)),
                ('zone', models.IntegerField(choices=[(-1, 'НетЗоны'), (0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')])),
                ('coefficient', models.FloatField(default=1.0)),
                ('tariff_type', models.PositiveIntegerField(choices=[(1, 'STANDART'), (2, 'PRIORITY')])),
                ('time_min', models.PositiveSmallIntegerField(default=None, null=True)),
                ('time_max', models.PositiveSmallIntegerField(default=None, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.PickPointCityList')),
                ('kladr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kladr.Kladr')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
