# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-02 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_deliverydelay'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliverydelay',
            unique_together=set([('product_type', 'vendor')]),
        ),
    ]
