# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-01 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_auto_20180502_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydelay',
            name='product_type',
            field=models.CharField(blank=True, choices=[('', 'Не задано'), ('CUBE', 'CUBE')], default='', max_length=128, verbose_name='Тип продукта'),
        ),
    ]
