# Generated by Django 2.1.4 on 2019-09-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_resolved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('refund', 'Возврат')], default='pending', max_length=32),
        ),
    ]
