# Generated by Django 2.1.4 on 2019-07-02 15:06

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.IntegerField(db_index=True)),
                ('uuid', models.CharField(db_index=True, max_length=128)),
                ('manager_notes', models.TextField(blank=True)),
                ('client_notes', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('cart', django.contrib.postgres.fields.jsonb.JSONField()),
                ('location', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('customer', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('delivery', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('cpa', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('store', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('tracking', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('payment', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
