# Generated by Django 2.1.4 on 2019-07-18 12:22

import cart.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modified_at', models.DateTimeField(blank=True, verbose_name='last modification date')),
                ('public_id', models.IntegerField(db_index=True)),
                ('uuid', models.CharField(db_index=True, max_length=128)),
                ('manager_notes', models.TextField(blank=True)),
                ('client_notes', models.TextField(blank=True)),
                ('state', models.IntegerField(choices=[(1, 'Новый'), (2, 'Недозвон'), (3, 'Недозвон_2'), (4, 'Доставка'), (5, 'Согласован'), (6, 'Выполнен'), (7, 'Отменён'), (8, 'Отменён: недозвон'), (9, 'Вручен'), (10, 'Отказ')], default=1)),
                ('source', models.IntegerField(choices=[(1, 'Неизвестно'), (2, 'Корзина'), (3, 'Быстрая покупка'), (4, 'Страница категории')], default=1)),
                ('cart', django.contrib.postgres.fields.jsonb.JSONField()),
                ('location', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('customer', django.contrib.postgres.fields.jsonb.JSONField(default=cart.models._empty_customer)),
                ('delivery', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('cpa', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('store', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('tracking', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('payment', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
