# Generated by Django 2.1.4 on 2019-07-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='_order',
            field=models.IntegerField(default=10, verbose_name='порядок'),
        ),
    ]
