# Generated by Django 2.1.4 on 2019-07-08 13:04

import cart.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20190704_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=cart.models._empty_customer),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, choices=[(1, 'Неизвестно'), (2, 'Корзина'), (3, 'Быстрая покупка'), (4, 'Страница категории')], default=1, max_length=128),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, choices=[(1, 'Новый'), (2, 'Недозвон'), (3, 'Недозвон_2'), (4, 'Доставка'), (5, 'Согласован'), (6, 'Выполнен'), (7, 'Отменён'), (8, 'Отменён: недозвон'), (9, 'Вручен'), (10, 'Отказ')], default=1, max_length=128),
        ),
    ]
