# Generated by Django 2.1.4 on 2019-07-20 15:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order__order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sale',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
