# Generated by Django 2.1.4 on 2019-08-14 11:20

import cart.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sale',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=cart.models._empty_sale),
        ),
    ]
