# Generated by Django 2.1.4 on 2019-08-16 14:33

import core.db.fields.integer_range_field
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0004_auto_20190814_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modified_at', models.DateTimeField(blank=True, verbose_name='last modification date')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('datatype', models.PositiveSmallIntegerField(choices=[(1, 'По брендам'), (2, 'По коллекциям'), (3, 'Приватный'), (4, 'Вручную')], default=1)),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField(blank=True)),
                ('is_permament', models.BooleanField(default=False)),
                ('brands', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('series', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('has_limited_use', models.BooleanField(default=False)),
                ('limit', models.PositiveSmallIntegerField(default=1)),
                ('sale_amount', core.db.fields.integer_range_field.PositiveSmallIntegerRangeField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User2PromocodeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='promocode',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='promocodes', through='cart.User2PromocodeRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
