# Generated by Django 2.1.4 on 2019-07-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'Недозвон'), (3, 'Недозвон_2'), (4, 'Доставка'), (5, 'Согласован'), (6, 'Выполнен'), (7, 'Отменён'), (8, 'Отменён: недозвон'), (9, 'Вручен'), (10, 'Отказ')], default=1),
        ),
    ]
