# Generated by Django 2.1.4 on 2019-07-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='source',
        ),
    ]
