# Generated by Django 2.1.4 on 2019-10-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by_staff',
            field=models.BooleanField(default=False),
        ),
    ]
