# Generated by Django 2.1.4 on 2019-12-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_GiftPromocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
