# Generated by Django 2.1.4 on 2019-12-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_PromocodeApplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='datatype',
            field=models.PositiveSmallIntegerField(choices=[(1, 'По брендам'), (2, 'По коллекциям'), (3, 'Приватный'), (4, 'Вручную'), (5, 'Вам подарок'), (6, 'Триггерный')], default=1),
        ),
    ]
